# Generated by Django 4.1.7 on 2023-03-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["name"],
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Город", "verbose_name_plural": "Города"},
        ),
    ]

